apiVersion: apps/v1
kind: Deployment
metadata:
 name: order-service
 labels:
  app: orderservice
spec:
 replicas: 1
 selector:
  matchLabels:
   app: orderservice
 template:
  metadata:
   labels:
    app: orderservice
  spec:
   containers:
    - name: orderservice-container
      image: onkarsngh11/userservice:orderservicev1
      ports:
       - containerPort: 9000